### ISSUE TITLE
Опечатка (с. 65)

### ISSUE THREAD

**Issue by SharanovPavel** [IRus/social-architecture-ru#8]
Написано: "Искажение цитаты Столлмана: «ваша свобода создавать _идеальная_ мир заканчивается в дюйме от моего приложения»."

Правильно: "Искажение цитаты Столлмана: «ваша свобода создавать _идеальный_ мир заканчивается в дюйме от моего приложения»."

**Comment by IRus** [comment]
Спасибо, исправил
